name: climate_data_api
description: Climate data api app.
# version: 1.0.0
# homepage: https://www.example.com
# author: ksokolovskyi <konstantin.sokolovskyi@711media.de>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  xml: 3.7.0
  servirtium:
    git:
      url: https://github.com/servirtium/servirtium-dart.git
      path: servirtium

dev_dependencies:
  test: ^1.12.0
